import { StyleSheet } from "react-native";

const Roboto = "Roboto-Regular";

const styles = StyleSheet.create({
  authBacground: {
    backgroundColor: "#fff",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    padding: 16,
    paddingBottom: 78,
  },
  background: {
    width: "100%",
    height: "100%",
  },
  addAvatarButton: {
    width: 25,
    height: 25,
    borderRadius: 999,
    borderColor: "#FF6C00",
    borderStyle: "solid",
    borderWidth: 1,
    left: 107,
    top: 81,
    right: 0,
    bottom: 14,
    padding: 5.5,
  },
  addAvatarButtonIcon: {
    width: 13,
    height: 13,
  },
  avatarBackground: {
    width: 120,
    height: 120,
    position: "relative",
    top: 0,
    left: "50%",
    transform: [{ translateX: -61 }, { translateY: -61 }],
    backgroundColor: "#F6F6F6",
    borderRadius: 16,
    marginBottom: -61,
  },
  registrationHeader: {
    color: "#212121",
    textAlign: "center",
    fontSize: 30,
    fontStyle: "normal",
    fontWeight: 500,
    letterSpacing: 0.3,
    fontFamily: Roboto,
    marginTop: 32,
    marginBottom: 33,
  },
  authInputs: {
    fontFamily: Roboto,
    marginTop: 16,
    backgroundColor: "#F6F6F6",
    borderColor: "#E8E8E8",
    borderStyle: "solid",
    borderWidth: 1,
    height: 50,
    borderRadius: 8,
    padding: 16,
  },
  authInputsFocus: {
    borderColor: "#FF6C00",
    borderWidth: 1,
    backgroundColor: "#fff",
  },
  sendButton: {
    backgroundColor: "#FF6C00",
    marginTop: 43,
    padding: 16,
    borderRadius: 100,
  },
  sendButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: 400,
    fontFamily: Roboto,
    textAlign: "center",
  },
  textLikeLink: {
    color: "#1B4371",
    fontSize: 16,
    fontFamily: Roboto,
    fontWeight: 400,
  },
  showPasswordButton: {
    position: "absolute",
    right: 16,
    top: 16,
  },
  showPasswordText: {
    color: "#1B4371",
    fontFamily: Roboto,
    fontSize: 16,
    fontWeight: 400,
  },
  avatarBackgroundPostsScreen: {
    width: 60,
    height: 60,
    backgroundColor: "#F6F6F6",
    borderRadius: 16,
    marginRight: 8,
  },
  logoutPostsScreeen: {
    position: "absolute",
    bottom: 10,
    right: 16,
  },
  postsScreenHeader: {
    padding: 16,
    paddingTop: 44,
    paddingBottom: 11,
    borderBottomColor: "#000",
    borderBottomWidth: 1,
  },
  postsScreenHeaderText: {
    color: "#212121",
    textAlign: "center",
    fontFamily: Roboto,
    fontSize: 17,
    fontStyle: "normal",
    fontWeight: 500,
  },
  postsScreenBody: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    height: `${641 / 8.12}%`,
    display: "flex",
    flexDirection: "column",
  },
  postImage: {
    width: "100%",
    height: 240,
    borderRadius: 8,
  },
  posts: {
    width: "auto",
    height: "auto",
    marginTop: 34,
    marginBottom: 34,
    display: "flex",
    flexDirection: "column",
  },
  postMoreInformationBlock: {
    display: "flex",
    flexDirection: "row",
    alignContent: "space-between",
    justifyContent: "space-between",
  },
  postMoreInformationText: {
    marginTop: 8,
    marginBottom: 8,
    color: "#212121",
    fontFamily: Roboto,
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: 500,
  },
  createPostsText: {
    color: "#BDBDBD",
    fontFamily: Roboto,
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: 400,
  },
  createPostsInput: {
    height: 50,
    borderBottomColor: "#E8E8E8",
    borderBottomWidth: 1,
    fontFamily: Roboto,
  },
  createPostsButtonAdd: {
    position: "absolute",
    borderRadius: 60,
    width: 60,
    height: 60,
    top: "50%",
    left: "50%",
    transform: [{ translateX: -30 }, { translateY: -30 }],
  },
  createPostsButtonAddImage: {
    width: 20,
    height: 18,
    position: "relative",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -10 }, { translateY: -9 }],
  },
  createPostsButtonCreate: {
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 100,
    display: "flex",
    alignItems: "center",
  },
  createPostsButtonCreateText: {
    fontFamily: Roboto,
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: 400,
  },
});

export default styles;
